### ISSUE TITLE
Goblin Audio has no drop off with distance

### ISSUE THREAD

**Issue by Ichofox** [NickSuttonDicken/FantasyOrigins#1]
Basically, if a goblin's in a loaded chunk, then regardless of the distance between me and it, it sounds like it's right by me.

**Comment by NickSuttonDicken** [comment]
I'll have a look when I get some free time.

**Comment by NickSuttonDicken** [comment]
Issue has been revolved and patch has been released on Curseforge (Pending approval), thanks for letting me know.
