### ISSUE TITLE
1.18.1 pixie origin not appearing

### ISSUE THREAD

**Issue by Pigeon-boi** [NickSuttonDicken/FantasyOrigins#12]
for the 1.18 version the pixie isn't appearing as an option, all the others are and this is happening in both single player and on servers.

**Comment by NickSuttonDicken** [comment]
This mod doesn't have a Pixie Origin??

**Comment by Pigeon-boi** [comment]
sorry just realised I had several similar mod pages open and put the complaint on the wrong one, apologies
