### ISSUE TITLE
Dwarves are basically unplayable? Clipping(?) issues

### ISSUE THREAD

**Issue by Shinyrussian** [NickSuttonDicken/FantasyOrigins#5]
Playing on a fabric server with some friends, selected dwarf to begin and seemed fine at first. However once you move up against a block and then try to jump you get locked in place and just kind of vibrate(?) as your character tries to jump but can't. I'm assuming that due to the size of the player model changing that we are somehow getting inside the blocks and then it is limiting movement. This basically means that you can't hold forward and jump over stuff as you get to it or really move at all when you are up against blocks. Also tried it in a singleplayer world just to check and have I still have the same issue. Not sure if others are having this issue but I wanted to at least let people know it was an issue so hopefully it can get fixed in the future. The Dwarf just seemed like a fun race with nice strengths and just enough things to work around that it would change the game but not super restrictively.

**Comment by NickSuttonDicken** [comment]
Weird, seems to be an issue between Extra Origins and Pehkui, I've noticed that crouching after swapping to any Origin with the issue seems to resolve it. I'll contact the Extra Origins developer and see what they think. Thanks for letting me know

**Comment by NickSuttonDicken** [comment]
Have spoken to the Pehkui developer and they said it's a known bug and they'll be fixing it this coming weekend. I'll leave this open until it has been resolved on their end though.

**Comment by Shinyrussian** [comment]
Cool! Thank you for taking the time to reach out to them! Sorry for bothering you with it when it wasn't actually an issue on your end though. I'm glad it's going to be resolved :D
