### ISSUE TITLE
Triten cannot respawn

### ISSUE THREAD

**Issue by Redprawn** [NickSuttonDicken/FantasyOrigins#9]
Hello
I was palying as a Triten and I found that I'm not able to respawn in single and multyplayer.
Could you fix this bug? Thank you very much.

**Comment by Zunwolf1896** [comment]
I have also found this issue with my server, I had a similar issue with an origin that spawned in the end, it was due to the "end_city" being labeled wrong in the datapack, I assume it is a similar issue here.

**Comment by NickSuttonDicken** [comment]
For some reason it didn't accept "ocean_ruin" so I've changed it to "ocean_ruin_warm", will be patching today.
